USE SistemaIngresos;
GO

/*
El semáforo depende únicamente del tiempo transcurrido desde la última
donación cobrada. El estatus del donante y las promesas activas no alteran
el nivel de riesgo.
*/
CREATE OR ALTER VIEW dbo.VW_DONANTE_INDICADORES
AS
WITH HOY AS (
    SELECT CAST(GETDATE() AS DATE) AS FECHA
),
COBROS AS (
    SELECT dv.ID_DONANTE,
           b.FECHA_PAGO,
           b.FECHA_VENCIMIENTO,
           b.IMPORTE_COBRADO,
           ep.NOMBRE AS ESTATUS
    FROM dbo.OPE_BITACORA_PAGOS_DONATIVOS b
    JOIN dbo.OPE_DONATIVOS_DONANTE dv ON dv.ID_DONATIVO = b.ID_DONATIVO
    JOIN dbo.CAT_ESTATUS_PAGO ep      ON ep.ID_ESTATUS_PAGO = b.ESTATUS_PAGO
),
RESUMEN_COBROS AS (
    SELECT c.ID_DONANTE,
           MAX(CASE WHEN c.ESTATUS = N'COBRADO' THEN c.FECHA_PAGO END) AS ULTIMA_DONACION,
           SUM(CASE WHEN c.ESTATUS = N'COBRADO' AND c.FECHA_PAGO > DATEADD(MONTH, -12, h.FECHA)
                    THEN c.IMPORTE_COBRADO ELSE 0 END) AS ACUMULADO_12_MESES,
           AVG(CASE WHEN c.ESTATUS = N'COBRADO' THEN c.IMPORTE_COBRADO END) AS MONTO_PROMEDIO,
           SUM(CASE WHEN c.ESTATUS = N'RECHAZADO'
                      OR (c.ESTATUS = N'PENDIENTE' AND c.FECHA_VENCIMIENTO < h.FECHA)
                    THEN 1 ELSE 0 END) AS COBROS_VENCIDOS
    FROM COBROS c
    CROSS JOIN HOY h
    GROUP BY c.ID_DONANTE
),
PROMESAS_ACTIVAS AS (
    SELECT DISTINCT dv.ID_DONANTE
    FROM dbo.OPE_DONATIVOS_DONANTE dv
    JOIN dbo.CAT_ESTATUS_DONATIVO es ON es.ID_ESTATUS = dv.ID_ESTATUS
    WHERE es.NOMBRE = N'ACTIVO'
),
INDICADORES AS (
    SELECT d.ID_DONANTE,
           COALESCE(d.RAZON_SOCIAL, CONCAT_WS(N' ', d.NOMBRE, d.A_PATERNO, d.A_MATERNO)) AS NOMBRE_DONANTE,
           d.ESTATUS_DONANTE,
           d.FECHA_ALTA,
           rc.ULTIMA_DONACION,
           ISNULL(rc.ACUMULADO_12_MESES, 0) AS ACUMULADO_12_MESES,
           ISNULL(rc.MONTO_PROMEDIO, 0) AS MONTO_PROMEDIO,
           ISNULL(rc.COBROS_VENCIDOS, 0) AS COBROS_VENCIDOS,
           CAST(CASE WHEN pa.ID_DONANTE IS NULL THEN 0 ELSE 1 END AS BIT) AS TIENE_PROMESA_ACTIVA,
           CASE
               WHEN rc.ULTIMA_DONACION IS NULL THEN N'ROJO'
               WHEN rc.ULTIMA_DONACION >= DATEADD(MONTH, -1, h.FECHA) THEN N'VERDE'
               WHEN rc.ULTIMA_DONACION >= DATEADD(MONTH, -6, h.FECHA) THEN N'AMARILLO'
               WHEN rc.ULTIMA_DONACION >= DATEADD(MONTH, -12, h.FECHA) THEN N'NARANJA'
               ELSE N'ROJO'
           END AS NIVEL_RIESGO
    FROM dbo.OPE_DONANTES d
    CROSS JOIN HOY h
    LEFT JOIN RESUMEN_COBROS rc ON rc.ID_DONANTE = d.ID_DONANTE
    LEFT JOIN PROMESAS_ACTIVAS pa ON pa.ID_DONANTE = d.ID_DONANTE
)
SELECT i.*,
       CAST(CASE WHEN i.NIVEL_RIESGO <> N'VERDE' THEN 1 ELSE 0 END AS BIT) AS EN_RIESGO,
       CAST(CASE WHEN i.ACUMULADO_12_MESES > 0
                  AND PERCENT_RANK() OVER (ORDER BY i.ACUMULADO_12_MESES) >= 0.9
                 THEN 1 ELSE 0 END AS BIT) AS ALTO_VALOR
FROM INDICADORES i;
GO
